 type: web
    name: memefast-api-proxy
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm run start
      staticPublishPath: dist
    plan: free
    envVars:
      - key: NODE_VERSION
        value: 18.17.0
      - key: PORT
        value: 10000
